door_uul = {type=Tile.Solid, frame=1}
door_uur = {type=Tile.Solid, frame=2}
container_01 = {type=Tile.Solid, frame=3}
container_02 = {type=Tile.Solid, frame=4}
container_03 = {type=Tile.Solid, frame=5}
container_04 = {type=Tile.Solid, frame=6}
floor_l = {type=Tile.Solid, frame=7}
floor_m = {type=Tile.Solid, frame=8}
floor_r = {type=Tile.Solid, frame=9}
railing_u = {type=Tile.Solid, frame=10}
door_ul = {type=Tile.Solid, frame=11}
door_ur = {type=Tile.Solid, frame=12}
container_05 = {type=Tile.Solid, frame=13}
container_06 = {type=Tile.Solid, frame=14}
container_07 = {type=Tile.Solid, frame=15}
container_08 = {type=Tile.Solid, frame=16}
brick_l = {type=Tile.Solid, frame=17}
brick_m = {type=Tile.Solid, frame=18}
brick_r = {type=Tile.Solid,frame=19}
railing_m = {type=Tile.Solid, frame=20}
door_dl = {type=Tile.Solid, frame=21}
door_dr = {type=Tile.Solid, frame=22}
container_09 = {type=Tile.Solid, frame=23}
container_10 = {type=Tile.Solid, frame=24}
container_11 = {type=Tile.Solid, frame=25}
container_12 = {type=Tile.Solid, frame=26}
flower_l = {type=Tile.Empty, frame=27}
flower_r = {type=Tile.Empty, frame=28}
brickfloor_s = {type=Tile.Solid, frame=29}
railing_d = {type=Tile.Solid, frame=30}
door_ddl = {type=Tile.Solid, frame=31}
door_ddr = {type=Tile.Solid, frame=32}
container_13 = {type=Tile.Solid, frame=33}
container_14 = {type=Tile.Solid, frame=34}
container_15 = {type=Tile.Solid, frame=35}
container_16 = {type=Tile.Solid, frame=36}
pot_l = {type=Tile.Solid, frame=37}
pot_r = {type=Tile.Solid, frame=38}
brickfloor = {type=Tile.Solid, frame=39}
box_1 = {type=Tile.Solid, frame=40}
box_2 = {type=Tile.Solid, frame=41}
box_3 = {type=Tile.Solid, frame=42}
box_4 = {type=Tile.Solid, frame=43}
black_l = {type=Tile.Empty, frame=44}
black = {type=Tile.Solid, frame=45}
black_hole = {type=Tile.Solid, frame=46}
black_r = {type=Tile.Empty, frame=47}
ledge_x = {type=Tile.Ledge, frame=48}
ledge = {type=Tile.Ledge, frame=49}
floor_ledge_l = {type=Tile.Ledge, frame=50}
floor_ledge_r = {type=Tile.Ledge, frame=51}