empty_l = {type=Tile.Empty, frame=1}
sand_top = {type=Tile.Solid, frame=2}
empty_r = {type=Tile.Empty, frame=3}
sand_dl = {type=Tile.Solid, frame=4}
sand_d = {type=Tile.Solid, frame=5}
sand_dr = {type=Tile.Solid, frame=6}
dirt_ul = {type=Tile.Solid, frame=7}
dirt_u = {type=Tile.Solid, frame=8}
dirt_ur = {type=Tile.Solid, frame=9}
block_ull = {type=Tile.Solid, frame=10}
block_ul = {type=Tile.Solid, frame=11}
block_u = {type=Tile.Solid, frame=12}
block_ur = {type=Tile.Solid, frame=13}
block_urr = {type=Tile.Solid, frame=14}
slope_l = {type=Tile.Solid, frame=15}
slope_r = {type=Tile.Solid, frame=16}
slope_dark_l = {type=Tile.Empty, frame=17}
sope_dark_r = {type=Tile.Empty, frame=18}
slope_dirt_r = {type=Tile.Solid, frame=19}

dummy20 = {type=Tile.Empty, frame=20}
sand_l = {type=Tile.Solid, frame=21}
sand = {type=Tile.Solid, frame=22}
sand_r = {type=Tile.Solid, frame=23}
sand_ddl = {type=Tile.Solid, frame=24}
blockdark = {type=Tile.Empty, frame=25}
sand_ddr = {type=Tile.Solid, frame=26}
dirt_l = {type=Tile.Solid, frame=27}
dirt = {type=Tile.Solid, frame=28}
dirt_r = {type=Tile.Solid, frame=29}
block_ll = {type=Tile.Solid, frame=30}
block_l = {type=Tile.Solid, frame=31}
block_cr = {type=Tile.Solid, frame=32}
block_r = {type=Tile.Solid, frame=33}
block_rr = {type=Tile.Solid, frame=34}
slope_sand_l = {type=Tile.Solid, frame=35}
slope_sand_r = {type=Tile.Solid, frame=36}
floor_l = {type=Tile.Solid, frame=37}
floor_r = {type=Tile.Solid, frame=38}
floor_dark_ur = {type=Tile.Solid, frame=39}

cloud_l = {type=Tile.Empty, frame=40}
cloud = {type=Tile.Sticky, frame=41}
cloud_r = {type=Tile.Empty, frame=42}
cloud_ledge = {type=Tile.Ledge, frame=43}
sand_dddl = {type=Tile.Solid, frame=44}
line = {type=Tile.Empty, frame=45}
sand_dddr = {type=Tile.Solid, frame=46}
dirt_dl = {type=Tile.Solid, frame=47}
line_dark = {type=Tile.Solid, frame=48}
dirt_dr = {type=Tile.Solid, frame=49}
block_dll = {type=Tile.Solid, frame=50}
block_dl = {type=Tile.Solid, frame=51}
block_d = {type=Tile.Solid, frame=52}
block_dr = {type=Tile.Solid, frame=53}
block_drr = {type=Tile.Solid, frame=54}
dummy55 = {type=Tile.Solid, frame=55}
dummy56 = {type=Tile.Solid, frame=56}
dummy57 = {type=Tile.Solid, frame=57}
dummy58 = {type=Tile.Solid, frame=58}
floor_dark_r = {type=Tile.Solid, frame=59}

glyph_a = {type=Tile.Solid, frame=60}
glyph_b = {type=Tile.Solid, frame=61}
glyph_c = {type=Tile.Solid, frame=62}
glyph_d = {type=Tile.Solid, frame=63}
glyph_e = {type=Tile.Solid, frame=64}
glyph_f = {type=Tile.Solid, frame=65}
glyph_g = {type=Tile.Solid, frame=66}
glyph_h = {type=Tile.Solid, frame=67}
glyph_i = {type=Tile.Solid, frame=68}
glyph_j = {type=Tile.Solid, frame=69}
glyph_k = {type=Tile.Solid, frame=70}
glyph_l = {type=Tile.Solid, frame=71}
glyph_m = {type=Tile.Solid, frame=72}
glyph_n = {type=Tile.Solid, frame=73}
cactus_u = {type=Tile.Empty, frame=74}
cactus_ll = {type=Tile.Empty, frame=75}
cactus_l = {type=Tile.Empty, frame=76}
cactus = {type=Tile.Empty, frame=77}
cactus_r = {type=Tile.Empty, frame=78}
cactus_rr = {type=Tile.Empty, frame=79}
